export const tourActionType = {
  //? GET ALL TOUR
  ALL_TOURS_REQUEST: "ALL_TOURS_REQUEST",
  ALL_TOURS_FAIL: "ALL_TOURS_FAIL",
  ALL_TOURS_SUCCESS: "ALL_TOURS_SUCCESS",


  //? GET A SINGLE TOUR
  TOUR_REQUEST: "TOUR_REQUEST",
  TOUR_FAIL: "TOUR_FAIL",
  TOUR_SUCCESS: "TOUR_SUCCESS",

  //? GET TOP 3 CHEAP TOUR
  TOP_TOUR_REQUEST: "TOP_TOUR_REQUEST",
  TOP_TOUR_FAIL: "TOP_TOUR_FAIL",
  TOP_TOUR_SUCCESS: "TOP_TOUR_SUCCESS",

  //? CREATE TOUR  -- ADMIN
  CREATE_TOUR_REQUEST: "CREATE_TOUR_REQUEST",
  CREATE_TOUR_FAIL: "CREATE_TOUR_FAIL",
  CREATE_TOUR_SUCCESS: "CREATE_TOUR_SUCCESS",

  //? DELETE TOUR  -- ADMIN
  DELETE_TOUR_REQUEST: "DELETE_TOUR_REQUEST",
  DELETE_TOUR_FAIL: "DELETE_TOUR_FAIL",
  DELETE_TOUR_SUCCESS: "DELETE_TOUR_SUCCESS",

  //? UPDATE TOUR  -- ADMIN
  UPDATE_TOUR_REQUEST: "UPDATE_TOUR_REQUEST",
  UPDATE_TOUR_FAIL: "UPDATE_TOUR_FAIL",
  UPDATE_TOUR_SUCCESS: "UPDATE_TOUR_SUCCESS",
};
