export const tourActionType = {
  ALL_TOURS_REQUEST: 'ALL_TOURS_REQUEST',
  ALL_TOURS_FAIL: 'ALL_TOURS_FAIL',
  ALL_TOURS_SUCCESS: 'ALL_TOURS_SUCCESS',
  TOUR_REQUEST: 'TOUR_REQUEST',
  TOUR_FAIL: 'TOUR_FAIL',
  TOUR_SUCCESS: 'TOUR_SUCCESS',
};
