export const reviewActionType = {
  ALL_REVIEW_REQUEST: "ALL_REVIEW_REQUEST",
  ALL_REVIEW_FAIL: "ALL_REVIEW_FAIL",
  ALL_REVIEW_SUCCESS: "ALL_REVIEW_SUCCESS",

  TOUR_REVIEW_REQUEST: "TOUR_REVIEW_REQUEST",
  TOUR_REVIEW_FAIL: "TOUR_REVIEW_FAIL",
  TOUR_REVIEW_SUCCESS: "TOUR_REVIEW_SUCCESS",
};
