export const bookingActionType = {
  //? GET ALL Booking
  ALL_BOOKING_REQUEST: "ALL_BOOKING_REQUEST",
  ALL_BOOKING_FAIL: "ALL_BOOKING_FAIL",
  ALL_BOOKING_SUCCESS: "ALL_BOOKING_SUCCESS",


  //? GET ALL Booking
  USER_BOOKING_REQUEST: "USER_BOOKING_REQUEST",
  USER_BOOKING_FAIL: "USER_BOOKING_FAIL",
  USER_BOOKING_SUCCESS: "USER_BOOKING_SUCCESS",

};
